name: build-deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
    - '.github/**'
    - 'README.md'
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
      - name: Build and Test
        run: |
          mvn clean compile
      - uses: actions/upload-artifact@v2
        with:
          name: action-package
          path: |
            target/*
  test:
    name: Test the action
    runs-on: ubuntu-latest
    needs: build       
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: action-package
    - uses: actions/setup-java@v1
      with:
       java-version: 11
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
    - name: run test
      run: |
        mvn test
  release:
    if: github.event_name == 'workflow_dispatch'
    name: Publish new release
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: build release
      run: |
        echo "Create release"
